my_environment_1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from users import views
from my_log import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('my_log.urls')),
    path('',views.index,name = 'index'),

]
urlpatterns+= static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

my_log/urls.py
from django.urls import path,include
from . import views


app_name = 'my_log'

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('create/', views.create, name='create'),
    path('updateorder/<str:pk>/', views.update_order, name='updateorder'),
    path('deleteorder/<str:pk>/', views.delete_order, name='deleteorder')

]

users/urls.py
from django.urls import path,include
from . import views


app_name = 'users'

urlpatterns = [
    path('login',views.login,name = 'login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),

]

templates/base/base.html
<!DOCTYPE html>
{% load static %}

<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}Base{% endblock %}</title>

    <!-- Bootstrap -->
      <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
       <link href="{% static 'css/my_nav.css' %}" rel="stylesheet">
      {% block css %}

      {% endblock %}


    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
    </head>
    <body>

  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
          <span class="sr-only"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>


      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="my-nav">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'my_log:index' %}">MY SHOP</a></li>
            <li><a href="">About the Web</a></li>
        </ul>

        <div class="pull-right">

          {% if user.is_authenticated %}

                Welcome: {{ user.username }}

            <span class="btn btn-sm btn-info"><a href="{% url 'users:change_password' %}"> 修改密码</a></span>
            <span class="item"><a href="{% url 'users:logout' %}"> 退出</a></span>


            {% else %}
                你好！请登录：
            <a class="btn btn-sm btn-info"  href="{% url 'users:login' %}">登录</a>

            {% endif %}

        </div>
      </div>

  </div>
</nav>
  <div class="adds">
    {% block add %}

    {% endblock add %}
  </div>

    {% block content %}


  {% endblock %}




    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>


    {% block javascript %}


    {% endblock %}
  </body>
</html>