my_environment_1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from users import views
from my_log import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('my_log.urls')),
    path('',views.index,name = 'index'),

]
urlpatterns+= static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

my_log/urls.py
from django.urls import path,include
from . import views


app_name = 'my_log'

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('create/', views.create, name='create'),
    path('updateorder/<str:pk>/', views.update_order, name='updateorder'),
    path('deleteorder/<str:pk>/', views.delete_order, name='deleteorder')

]

users/urls.py
from django.urls import path,include
from . import views


app_name = 'users'

urlpatterns = [
    path('login',views.login,name = 'login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('change_password/', views.change_password, name='change_password'),

]

my_log/models.py
from django.db import models

# Create your models here.


class Customer(models.Model):
    customer_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=30)
    email = models.EmailField()
    time_created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.customer_name


class Product(models.Model):
    CATEGORY = (
        ('Indoor','Indoor'),
        ('Outdoor','Outdoor')
    )

    product_name = models.CharField(max_length=30)
    price = models.CharField(max_length=30)
    category = models.CharField(max_length=30, choices=CATEGORY)
    description = models.TextField(blank=True,null=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name

class Order(models.Model):
    STATUS = (
        ('pending','pending'),
        ('out for dilivert','out for delivery'),
        ('Deivered','Delivered')
    )
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='c_order')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='p_order')
    time_created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=30,choices=STATUS)


class Add(models.Model):
    title = models.CharField(max_length=128, verbose_name='广告标题')
    description = models.TextField(max_length=256, blank=True, null=True, verbose_name='广告描述')
    img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='广告图')
    callback_url = models.URLField(null=True,blank=True,verbose_name='网络URL')
    time_created = models.DateTimeField(auto_now_add=True,verbose_name='发布时间')
    index = models.IntegerField(default=999,verbose_name='排序')
    location = models.CharField(max_length=50,verbose_name='位置')
    is_display = models.BooleanField(default=False,verbose_name='是否显示')


    class Meta:

        verbose_name = "广告"
        verbose_name_plural = '广告'


    def __str__(self):
        return self.title

my_log/forms.py
from django import forms
from django.forms import ModelForm
from .models import Customer,Order


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields =[
            'customer_name',
            'phone',
            'email'
        ]
        labels = {
            'customer_name': '姓名',
            'phone':'电话',
            'email':'邮箱'
        }
        widgets = {
            'customer_name': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'请输入姓名'
            }),
            'phone': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder': '请输入电话'
            }),
        'email': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '请输入邮箱'
        })

        }



class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields ='__all__'
        exclude = ['time_created']

        labels = {
            'customer': '顾客',
            'product': '产品',
            'status': '订单状态'
        }
        widgets = {
            'customer': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': '请输入顾客'
            }),
            'product': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': '请输入产品'
            }),
            'status': forms.Select(attrs={
                'class': 'form-control',
                'placeholder': '请输入状态'
            })

        }

my_log/views.py
from django.shortcuts import render,redirect
from . models import Customer,Product,Order,Add
from . forms import CustomerForm,OrderForm
# Create your views here.

def index(request):
    customer = Customer.objects.all()
    add_list = Add.objects.all()
    c_count = customer.count()

    order_p_count = Order.objects.filter(status = 'pending').count()
    order_d_count = Order.objects.filter(status='out for dilivert').count()
    order_w_count = Order.objects.filter(status='Deivered').count()

    order = Order.objects.all()
    o_count = order.count()

    c = 0
    last_five =[]
    for i in reversed(order):
        if c < 5:
            last_five.append(i)
            c+=1
        else:
            break


    if request.is_ajax and request.POST.get('order_del'):
        del_order_id = request.POST.get('order_del')
        del_order = Order.objects.get(id = del_order_id)
        del_order.delete()


    context = {
        'customer':customer,
        'add_list':add_list,
        'c_count':c_count,
        'order':order,
        'order_p_count':order_p_count,
        'order_d_count':order_d_count,
        'order_w_count': order_w_count,
        'o_count': o_count,


        'last_five':last_five
    }

    return render(request,'my_log/index.html',context)




def create(request):
    c_form = CustomerForm()
    o_form =  OrderForm()

    if request.method == 'POST':
        if 'c-button' in request.POST:
            c_form = CustomerForm(request.POST)
            if c_form.is_valid():
                name_get = c_form.cleaned_data['customer_name']
                phone_get = c_form.cleaned_data['phone']
                email_get =c_form.cleaned_data['email']
                customer = Customer.objects.create(customer_name = name_get,phone = phone_get,email =email_get)
                customer.save()
                return redirect('index')

        if 'o-button' in request.POST:
            o_form = OrderForm(request.POST)
            if o_form.is_valid():
                customer_get = o_form.cleaned_data['customer']
                product_get = o_form.cleaned_data['product']
                status_get = o_form.cleaned_data['status']
                order = Order.objects.create(customer=customer_get,product = product_get,status = status_get)
                order.save()
                return redirect('index')


    context = {
        'c_form':c_form,
        'o_form': o_form

    }


    return render(request,'my_log/create.html',context)


def update_order(request,pk):
    order = Order.objects.get(id=pk)

    o_form = OrderForm(instance=order)

    if request.method == 'POST':
        o_form = OrderForm(request.POST)
        if o_form.is_valid():
            customer_get = o_form.cleaned_data['customer']
            product_get = o_form.cleaned_data['product']
            status_get = o_form.cleaned_data['status']
            order = Order.objects.filter(id = pk).update(id = pk, customer=customer_get, product=product_get, status=status_get)
            # order.save()
            return redirect('index')

    context = {
        'order': order,
        'o_form': o_form

    }


    return render(request,'my_log/updateorder.html',context)



def delete_order(request,pk):
    order = Order.objects.get(id = pk)


    if request.method =='POST':
        order.delete()


        return redirect('home')


    context = {
        'order': order,


    }
    return render(request,'my_log/deleteorder.html',context)

templates/my_log/add1.html
<div class="a1-ad">
    <div class="ads">
       <div style="padding-top: 70px; margin-left: 40px;">
           {% for ad in add_list %}
                {% if ad.location == 'a1' %}

                    <a target="_blank" href="{{ ad.callback.url }}"><img src="{{ ad.img.url }}" alt="广告图片" width="100%" class="ad1_img" ></a>
                {% endif %}
           {% endfor %}
       </div>

    </div>
</div>

templates/my_log/add2.html
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/lubotu.css' %}">
{% endblock css %}

<div class="main">
            <div class="focus f1">
                <!-- 左侧按钮 -->
                <a href="javascript:;" class="arrow-l">&lt;</a>
                <!-- 右侧按钮 -->
                <a href="javascript:;" class="arrow-r">&gt;</a>
                <ul>
                    <!-- 核心的滚动去 -->
                    {% for ad in add_list %}
                        {% if ad.location == 'a2' %}
                    <li>
                        <p class="zhanzhuai_title">{{ ad.title }}</p>
                         <a href="{{ ad.callback.url }}"><img src="{{ ad.img.url }}"  ></a>


                    </li>

                        {% endif %}
                    {% endfor %}


                </ul>
                <ol class="circle">

                </ol>
            </div>
        </div>






{% block javascript %}
<script src="{% static 'js/animate.js' %}"></script>
<script src="{% static 'js/slide.js' %}"></script>


{% endblock javascript %}

templates/my_log/create.html
{% extends 'base/base.html' %}

{% block title %}用户订单{% endblock %}

{% block content %}
<hr>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card shadow">
                <div class="card-header">
                    <h3 class="cart-title">Customer Form</h3>


                </div>
                <div class="card-body">
                    <form action="{% url 'my_log:create' %}" method="post">
                        {% csrf_token %}
                        {{ c_form.as_p }}
                        <div class="text-center">
                            <button type="submit" name="c-button"class="btn btn-primary">提交</button>
                        </div>
                    </form>
                </div>
            </div>
            </div>


        </div>
        <div class="col-md-6">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="card shadow">
                <div class="card-header">
                    <h3 class="cart-title">Order Form</h3>


                </div>
                <div class="card-body">
                     <form action="{% url 'my_log:create' %}" method="post">
                         {% csrf_token %}
                        {{ o_form.as_p }}
                        <div class="text-center">
                            <button type="submit" name="o-button" class="btn btn-primary">提交</button>
                        </div>
                    </form>
                </div>
            </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/my_log/deleteorder.html
{% extends 'base/base.html' %}

{% block title %}删除{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div style="height: 100px;"></div>
            <div class="card shadow">
                <div class="card-body text-center">
                    <h1>你确定要删除这个订单吗？</h1>

                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Customer</th>
                                <th scope="col">Product</th>
                                <th scope="col">Status</th>

                            </tr>
                        </thead>
                        <tbody>

                            <tr>

                                <td>{{ order.customer }}</td>
                                <td>{{ order.product }}</td>
                                <td>{{ order.status }}</td>

                            </tr>

                        </tbody>
                    </table>




                    <form action="{% url 'my_log:deleteorder' order.id %}" method="post">
                        {% csrf_token %}
                        <a href="{% url 'my_log:index' %}" class="btn btn-warning">取消</a>
                        <button type="submit" class="btn btn-danger">确定</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/my_log/index.html
{% extends 'base/base.html' %}
{% load static %}


{% block title %}首页{% endblock %}

{% block add %}
 {% include 'my_log/add1.html' %}
{% endblock add %}

{% block content %}
<div style="height: 30px;"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            <div class="card bg-info shadow text-center">
                <div class="card-header">
                    <h1 class="card-title">Total Order</h1>
                </div>
                <div class="card-body">
                    <h3>{{ o_count }}</h3>
                </div>

            </div>
        </div>
        <div class="col-md-3">
            <div class="card bg-info shadow text-center">
                <div class="card-header">
                    <h1 class="card-title">Order-Delivered</h1>
                </div>
                <div class="card-body">
                    <h3>{{ order_w_count }}</h3>
                </div>

            </div>
        </div>
            <div class="col-md-3">
                <div class="card bg-info shadow text-center">
                    <div class="card-header">
                        <h1 class="card-title">Order-Pending</h1>
                    </div>
                    <div class="card-body">
                        <h3>{{ order_p_count }}</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card bg-info shadow text-center">
                    <div class="card-header">
                        <h1 class="card-title">Out of Delivery</h1>
                    </div>
                    <div class="card-body">
                        <h3>{{ order_d_count }}</h3>
                    </div>
                </div>
            </div>
    </div>
</div>
<hr>
<div style="height: 30px;"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <h3>Total Customer: {{ c_count}}</h3>
        </div>
        <div class="col-md-6">
            <a href="{% url 'my_log:create' %}" class="btn btn-lg btn-primary">Create Customer or Order</a>
        </div>
    </div>

</div>
<hr>
<div style="height: 30px;"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 text-center">
            <h3>
                Customer

            </h3>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">C_ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Phone</th>
                        <th scope="col">email</th>
                        <th scope="col">Time</th>
                        <th scope="col">View</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in customer reversed %}
                    <tr>
                        <th scope="row">{{ i.id }}</th>
                        <td>{{ i.customer_name }}</td>
                        <td>{{ i.phone }}</td>
                        <td>{{ i.email }}</td>
                        <td>{{ i.time_created }}</td>
                        <td>
                            <a href="" class="btn btn-small btn-info">View</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>


        </div>
        <div class="col-md-4">
            <div class="row">

                    {% include 'my_log/add2.html' %}

            </div>
        </div>
<!--       #第二个分割-->
        <div class="col-md-4 text-center">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                   <h4>Last 5 Order</h4>
                </div>
                <div class="col-md-4"></div>
            </div>

            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">O_ID</th>
                        <th scope="col">Customer</th>
                        <th scope="col">Product</th>
                        <th scope="col">Time</th>
                        <th scope="col">Status</th>
                        <th scope="col">Update</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for j in last_five %}
                    <tr>
                        <th scope="row">{{ j.id }}</th>
                        <td>{{ j.customer }}</td>
                        <td>{{ j.product}}</td>
                        <td>{{ j.time_created }}</td>
                        <td>{{ j.status }}</td>
                        <td>
                            <a href="{% url 'my_log:updateorder' j.id %}" class="btn btn-small btn-warning">update</a>
                        </td>
                        <td>

                            <button type="button" id="{{ j.id }}-del" class="btn btn-danger">remove</button>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}

    <script>
       {% for j in last_five %}

            $(document).ready(function() {
                $('#{{ j.id }}-del').click(function() {
                    var r = confirm("你要删除这个订单吗?")
                        if(r){
                            $.ajaxSetup({
                                data: {
                                    csrfmiddlewaretoken: '{{ csrf_token }}'
                                }
                            })
                            $.ajax ({
                                type: 'POST',
                                url: "{% url 'index' %}",
                                data: {
                                    'order_del': {{ j.id }}
                                },
                                dataType: 'text',
                                success: function() {
                                    window.location.reload()
                                },
                                error: function(){
                                    console.log('failed to load' )
                                }
                            })
                        }
                    })
                })

       {% endfor %}


    </script>



{% endblock %}

templates/my_log/updateorder.html
{% extends 'base/base.html' %}

{% block title %}更新{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div style="height: 100px; padding-top: 30px;"></div>
                <div class="card shadow">
                <div class="card-header text-center text-light bg-dark">
                    <h3 class="cart-title">Update Order</h3>


                </div>
                <div class="card-body">
                     <form action="{% url 'my_log:updateorder' order.id %}" method="post">
                         {% csrf_token %}
                        {{ o_form.as_p }}
                        <div class="text-center">
                            <button type="submit"  class="btn btn-primary">提交</button>
                        </div>
                    </form>
                </div>


            </div>

    </div>

</div>


{% endblock %}